stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
# variables:
  # pkgver: $PKGVER
  # pkgrel: $PKGREL
  # AARCH64: $AARCH64
  # X86_64: $X86_64

.carch_aarch64: &carch_aarch64
  variables:
    CARCH: 'aarch64'

.carch_x86_64: &carch_x86_64
  variables:
    CARCH: 'x86_64'

.tarball_build_config: &tarball_build_config
  stage: build
  script:
    - ./binary_tarball/build_tarball.sh "${CI_PROJECT_DIR}/LibreWolf-${pkgver}-${pkgrel}.${CARCH}.tar.bz2"
  artifacts:
    name: "Librewolf-Tarball-${pkgver}-${pkgrel}-${CARCH}"
    paths:
      - "LibreWolf-${pkgver}-${pkgrel}.${CARCH}.tar.bz2"

tarball_x86_64:
  image: ubuntu:16.04
  tags: [x86_64b]
  <<: *carch_x86_64
  <<: *tarball_build_config
  only:
    variables:
      - $X86_64

tarball_aarch64:
  image: arm64v8/ubuntu:16.04
  tags: [aarch64b]
  <<: *carch_aarch64
  <<: *tarball_build_config
  only:
    variables:
      - $AARCH64
